### ISSUE TITLE
Doesn't update tokens in repeater.

### ISSUE THREAD

**Issue by amroot** [elespike/burp-cph#19]
Hi, 

First, cool tool so thanks.

I'm likely doing this wrong but maybe not.

The goal is to update the request body with an obtained token for any API request that requires a token. Testing in repeater. Everything seems to work okay in debug but the token never gets updated in repeater and an error is thrown.

1. "Scope": Repeater 
2. "This tab will work only on requests that contain this expression:" \{\"token.*\} - request body needs token from below. JSON.
3. "Find matches": regex: \{\"token.*\}
4. "A value returned by issuing a single request": \{\"token.*\}

11:52:54:065 [DEBUG] is_request: 1
11:52:54:065 [DEBUG] rms_type_requests: 1
11:52:54:066 [DEBUG] rms_type_responses: 0
11:52:54:066 [DEBUG] rms_type_both: 0
11:52:54:066 [INFO] Sending request to tab "APILogin" for modification
11:52:54:066 [DEBUG] Extracted match values using this expression: \{\"token.*\}
11:52:54:068 [DEBUG] Final match values: [u'{"token":"***"}']
11:52:54:068 [DEBUG] Initial replace value: 
11:52:54:069 [DEBUG] Skipping message received from Extender on account of global tool scope options.
11:52:59:312 [DEBUG] Skipping message received from Extender on account of global tool scope options.
11:52:59:312 [DEBUG] Issued configured request from tab "APILogin" to host "***.***.***.***"
11:52:59:319 [DEBUG] Got response!
11:52:59:319 [DEBUG] Extracted replace value using this expression: \{\"token.*\}
11:52:59:319 [DEBUG] Replace value is now: {"token":"123"}
11:52:59:319 [DEBUG] Final replace value: {"token":"123"}
11:52:59:321 [DEBUG] Searching for "set([u'{"token":"111"}'])", inserting/replacing "{"token":"123"}"
11:52:59:321 [DEBUG] Unfiltered match indices: [0]
11:52:59:321 [DEBUG] Filtered match indices: set([0])
11:52:59:605 [DEBUG] is_request: 0
11:52:59:605 [DEBUG] rms_type_requests: 1
11:52:59:605 [DEBUG] rms_type_responses: 0
11:52:59:607 [DEBUG] rms_type_both: 0
11:52:59:607 [DEBUG] Preliminary scope check negative!
11:52:59:608 [DEBUG] is_request: 1
11:52:59:608 [DEBUG] rms_type_requests: 1
11:52:59:608 [DEBUG] rms_type_responses: 0
11:52:59:608 [DEBUG] rms_type_both: 0
11:52:59:608 [DEBUG] Messages cached for tab APILogin!

Traceback (most recent call last):
  File "./bapps/a/CustomParamHandler_merged.py", line 1728, in processHttpMessage
    modified_request = self.modify_message(tab, req_as_string)
  File "./bapps/a/CustomParamHandler_merged.py", line 1983, in modify_message
    substr_indices.extend([m.start() for m in finditer(match_value, original_msg)])
  File "/path/burp/jython-standalone-2.7.0.jar/Lib/re.py", line 186, in finditer
  File "/path/burp/jython-standalone-2.7.0.jar/Lib/re.py", line 242, in _compile
sre_constants.error: unexpected end of regular expression

	at org.python.core.PyException.doRaise(PyException.java:198)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.core.Py.makeException(Py.java:1341)
	at re$py._compile$12(/path/burp/jython-standalone-2.7.0.jar/Lib/re.py:246)
	at re$py.call_function(/path/burp/jython-standalone-2.7.0.jar/Lib/re.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:145)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at re$py.finditer$7(/path/burp/jython-standalone-2.7.0.jar/Lib/re.py:186)
	at re$py.call_function(/path/burp/jython-standalone-2.7.0.jar/Lib/re.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:145)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at org.python.pycode._pyx4.modify_message$108(./bapps/a/CustomParamHandler_merged.py:2012)
	at org.python.pycode._pyx4.call_function(./bapps/a/CustomParamHandler_merged.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx4.processHttpMessage$106(./bapps/a/CustomParamHandler_merged.py:1791)
	at org.python.pycode._pyx4.call_function(./bapps/a/CustomParamHandler_merged.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$19.processHttpMessage(Unknown Source)
	at burp.q2b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

Thanks!!!

**Comment by elespike** [comment]
Hi, @amroot!

At first glance, this may be related to the setup of the regular expression. Curly braces have special meaning, so you'll need to escape them when using RegEx. Try this, for instance:
`\{"token.*\}`

If that doesn't work, would you be able to export your CPH config and attach it here, along with a sample JSON/token that you'd like to extract?

**Comment by amroot** [comment]
I'm sorry, I modified my regex before posting to keep from relieving too much application functionality. I did have the brackets escaped.

I believe I figured out the bug though and I was able to reproduce it. If the regex .* in _"1) Find matches to this expression"_ returns something like JSON that contains brackets [ ] , it will produce an error. I shortened the regex to not return brackets in the response and it did not produce an error. 

sre_constants.error: unexpected end of regular expression

**Comment by elespike** [comment]
@amroot I've been unable to recreate the issue. Here's what I tried:

![cph_config](https://user-images.githubusercontent.com/14970655/29491899-43aadf4a-8538-11e7-888e-db9162a4ff1f.png)

![repeater](https://user-images.githubusercontent.com/14970655/29491900-4de83246-8538-11e7-9fa5-6df3829939ad.png)

CPH output:
```
23:35:53:509 [DEBUG] is_request: 1

23:35:53:510 [DEBUG] rms_type_requests: 1

23:35:53:510 [DEBUG] rms_type_responses: 0

23:35:53:510 [DEBUG] rms_type_both: 0

23:35:53:512 [INFO] Sending request to tab "Get token" for modification

23:35:53:513 [DEBUG] Extracted match values using this expression: \{"token.*\}

23:35:53:513 [DEBUG] Final match values: [u'{"token": "not_a_valid_token"}']

23:35:53:513 [DEBUG] Initial replace value: 

23:35:53:513 [DEBUG] Host is: 127.0.0.1

23:35:53:513 [DEBUG] Skipping message received from Extender on account of global tool scope options.

23:35:53:517 [DEBUG] Skipping message received from Extender on account of global tool scope options.

23:35:53:519 [DEBUG] Issued configured request from tab "Get token" to host "127.0.0.1"

23:35:53:522 [DEBUG] Got response!

23:35:53:523 [DEBUG] Extracted replace value using this expression: \{"token.*\}

23:35:53:523 [DEBUG] Replace value is now: {"token": "5a6dddbd-2cd4-4bae-86b3-0a1542e001a7"}

23:35:53:523 [DEBUG] Final replace value: {"token": "5a6dddbd-2cd4-4bae-86b3-0a1542e001a7"}

23:35:53:523 [DEBUG] Searching for "set([u'{"token": "not_a_valid_token"}'])", inserting/replacing "{"token": "5a6dddbd-2cd4-4bae-86b3-0a1542e001a7"}"

23:35:53:525 [DEBUG] Unfiltered match indices: [0]

23:35:53:525 [DEBUG] Filtered match indices: set([0])

23:35:53:525 [INFO] Match index [0]: matched "{"token": "not_a_valid_token"}", replaced with "{"token": "5a6dddbd-2cd4-4bae-86b3-0a1542e001a7"}"

23:35:53:526 [DEBUG] first_req_line_old is:
POST /post HTTP/1.1

23:35:53:526 [DEBUG] first_req_line_new is:
POST /post HTTP/1.1

23:35:53:532 [DEBUG] Actual first line of request is:
POST /post HTTP/1.1

23:35:53:535 [DEBUG] Forwarding request to host "127.0.0.1"

23:35:53:539 [DEBUG] is_request: 0

23:35:53:540 [DEBUG] rms_type_requests: 1

23:35:53:540 [DEBUG] rms_type_responses: 0

23:35:53:540 [DEBUG] rms_type_both: 0

23:35:53:540 [DEBUG] Preliminary scope check negative!

23:35:53:542 [DEBUG] is_request: 1

23:35:53:542 [DEBUG] rms_type_requests: 1

23:35:53:542 [DEBUG] rms_type_responses: 0

23:35:53:542 [DEBUG] rms_type_both: 0

23:35:53:542 [DEBUG] Messages cached for tab Get token!
```

**Comment by amroot** [comment]
Thanks for the detailed reply.

Add a JSON array with square brackets to your request. the square brackets returned in .* seem to cause the problem.

POST Request body:
`{ "token": {"access": "123","ids": "[]"}}`

**Comment by elespike** [comment]
@amroot, got it!

Pretty neat little bug you found. =)

Would you please try using the attached file and see if the problem is solved? Just rename it back to .py and load it into burp. I'll push the changes up to the repository once you confirm the fix.

[CustomParamHandler_merged.py.txt](https://github.com/elespike/burp-cph/files/1242736/CustomParamHandler_merged.py.txt)

**Comment by amroot** [comment]
That seems to work great, thanks!
